---
- name: Pre-taks | populate service ansible_facts
  service_facts:
- name: Pre-taks | Install pip (Debian)
  become: yes
  apt:
    name:
    - python3-pip
    - docker.io
    state: present
    update_cache: yes
  environment:
    use_proxy: "{{ use_proxy }}"
    http_proxy: "{{ http_proxy if use_proxy else '' }}"
    https_proxy: "{{ https_proxy if use_proxy else '' }}"
    no_proxy: "{{ no_proxy if use_proxy else '' }}"
  when: ansible_os_family == 'Debian'
# install EPEL, needed for python-pip in CentOS7
- name: Pre-taks | Install EPEL (RHEL)
  become: yes
  yum:
    name:
    - epel-release
    state: present
  environment:
    use_proxy: "{{ use_proxy }}"
    http_proxy: "{{ http_proxy if use_proxy else '' }}"
    https_proxy: "{{ https_proxy if use_proxy else '' }}"
    no_proxy: "{{ no_proxy if use_proxy else '' }}"
  when: ansible_distribution == 'CentOS'
- name: Pre-taks | Install pip (RHEL)
  become: yes
  yum:
    name:
    - python-pip
    - python3-pip
    - docker
    state: present
  environment:
    use_proxy: "{{ use_proxy }}"
    http_proxy: "{{ http_proxy if use_proxy else '' }}"
    https_proxy: "{{ https_proxy if use_proxy else '' }}"
    no_proxy: "{{ no_proxy if use_proxy else '' }}"
  when: ansible_os_family == 'RedHat'
- name: Pre-taks | Disable firewalld
  become: yes
  systemd:
    name: firewalld
    state: stopped
  when: ansible_facts.services['firewalld'] is defined
- name: Pre-taks | Changing state of selinux
  become: true
  selinux:
    policy: targeted
    state: permissive
  when: ansible_os_family == "RedHat"
- name: populate service ansible_facts
  service_facts:
- name: Ensure group "docker" exists
  become: yes
  group:
    name: docker
    state: present
- name: Add user to docker group
  become: yes
  user:
    name: "{{ ansible_ssh_user }}"
    groups:
    - docker
    append: yes
- name: Configure proxy on docker (1/3)
  become: yes
  ini_file:
    path: /etc/systemd/system/docker.service.d/http-proxy.conf
    section: Service
    option: Environment
    value: "\"HTTP_PROXY={{ http_proxy }}\""
    mode: '0600'
  when:
    - ansible_facts.services['docker.service'].source == "systemd"
    - use_proxy
- name: Configure proxy on docker (2/3)
  become: yes
  ini_file:
    path: /etc/systemd/system/docker.service.d/https-proxy.conf
    section: Service
    option: Environment
    value: "\"HTTPS_PROXY={{ https_proxy }}\""
    mode: '0600'
  when:
    - ansible_facts.services['docker.service'].source == "systemd"
    - use_proxy
- name: Configure proxy on docker (3/3)
  become: yes
  systemd:
    name: docker
    daemon_reload: yes
    state: reloaded
  when:
    - ansible_facts.services['docker.service'].source == "systemd"
    - use_proxy
- name: Ensure docker service is running
  become: yes
  systemd:
    name: docker
    daemon_reload: yes
    state: started
  when:
    - ansible_facts.services['docker.service'].source == "systemd"
